title: Blog about nothing

email: dorosch.github.io@yandex.ru

description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/"

google_analytics: false

url: "https://dorosch.github.io"

github_username:  dorosch

theme: minima

markdown: kramdown

highlighter: rouge
